package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"
	"stockels/graph/model"
	"stockels/module/stock"
	"stockels/module/user"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	fmt.Println("TESTING")
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, email string, password string) (string, error) {
	token, err := user.LoginService(email, password)
	return token, err
}

// GetStockData is the resolver for the getStockData field.
func (r *queryResolver) GetStockData(ctx context.Context, stocks []*model.GetStockData) ([]*model.StockData, error) {
	result, err := stock.GetMultipleStockService(stocks)
	return result, err
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
