package handlers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"stockels/app"
	"stockels/app/object"
	"stockels/app/services/analytic"
)

// GetFundamentalAnalytic is the resolver for the getFundamentalAnalytic field.
func (r *queryResolver) GetFundamentalAnalytic(ctx context.Context, symbol *string) (*object.Analytic, error) {
	return analytic.GetAnalyticFromAPI(*symbol)
}

// GetTechnicalAnalytic is the resolver for the getTechnicalAnalytic field.
func (r *queryResolver) GetTechnicalAnalytic(ctx context.Context, symbol string, fromYear int) (*object.TechnicalAnalytic, error) {
	return analytic.GetAnalyticStock(symbol, fromYear)
}

// Query returns app.QueryResolver implementation.
func (r *Resolver) Query() app.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
