// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GetStockData struct {
	StockSymbol     string `json:"stockSymbol"`
	SupportPrice    int    `json:"supportPrice"`
	ResistancePrice int    `json:"resistancePrice"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type StockData struct {
	Symbol               string  `json:"symbol"`
	Name                 string  `json:"name"`
	Description          string  `json:"description"`
	Sector               string  `json:"sector"`
	Logo                 string  `json:"logo"`
	Website              string  `json:"website"`
	OpenPrice            string  `json:"openPrice"`
	ClosePrice           string  `json:"closePrice"`
	HigestPrice          string  `json:"higestPrice"`
	LowestPrice          string  `json:"lowestPrice"`
	Volume               string  `json:"volume"`
	LastUpdate           string  `json:"lastUpdate"`
	SupportPercentage    float64 `json:"supportPercentage"`
	ResistancePercentage float64 `json:"resistancePercentage"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
