package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"stockels/graph"
	"stockels/graph/model"
	"stockels/graph/service"
)

// GetStockData is the resolver for the getStockData field.
func (r *queryResolver) GetStockData(ctx context.Context, stocks []*model.GetStockData) ([]*model.StockData, error) {
	result, err := service.GetMultipleStockService(stocks)
	return result, err
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
